# Generated by Django 4.2 on 2023-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_discounts', '0006_alter_discount_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность скидки'),
        ),
    ]
