# Generated by Django 4.2 on 2023-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_discounts', '0007_discount_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='процентная скидка'),
        ),
        migrations.AddField(
            model_name='discount',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='количественная скидка'),
        ),
        migrations.DeleteModel(
            name='DiscountPrice',
        ),
    ]
