# Generated by Django 4.2 on 2023-07-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_discounts', '0010_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
