# Generated by Django 4.2 on 2023-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Отзыв к товару', 'verbose_name_plural': 'Отзывы к товару'},
        ),
        migrations.AlterModelOptions(
            name='productinshop',
            options={'ordering': ['-id', 'shop', 'product', 'price'], 'verbose_name': 'Магазины и их товары', 'verbose_name_plural': 'Магазины и их товары'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления отзыва'),
        ),
    ]
