# Generated by Django 4.2 on 2023-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartregistereduser',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена товара со скидкой'),
        ),
    ]
