# Generated by Django 4.2 on 2023-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес доставки')),
                ('buying_type', models.CharField(choices=[('ordinary', 'Обычная доставка'), ('express', 'Экспресс доставка')], default='ordinary', max_length=100, verbose_name='Способ доставки')),
                ('payment', models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], default='online', max_length=100, verbose_name='Способ Оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('status', models.CharField(choices=[('paid for', 'Оплачен'), ('not paid', 'Не оплачен')], default='not paid', max_length=25, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
