# Generated by Django 4.2 on 2023-07-18 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_discounts', '0011_alter_coupon_options'),
        ('app_orders', '0002_rename_buying_type_order_delivery_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_discounts.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Обычная доставка', 'Обычная доставка'), ('Экспресс доставка', 'Экспресс доставка')], default='Обычная доставка', max_length=100, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Онлайн картой', 'Онлайн картой'), ('Онлайн со случайного чужого счета', 'Онлайн со случайного чужого счета')], default='Онлайн картой', max_length=100, verbose_name='Способ Оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Не оплачен', 'Не оплачен'), ('Оплачен', 'Оплачен')], default='Не оплачен', max_length=25, verbose_name='Статус заказа'),
        ),
    ]
