# Generated by Django 4.2 on 2023-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_rename_buying_type_order_delivery_order_user_and_more'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.ManyToManyField(related_name='users', to='app_orders.order', verbose_name='Заказы'),
        ),
    ]
