# Generated by Django 4.2 on 2023-07-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order',
        ),
    ]
